#ifndef ACHIEVEMENT_H
#define ACHIEVEMENT_H

#include <ostream>

namespace mmxpd {
    
    enum Achievement : unsigned short {
        DEFEATED_ARMORED_ARMADILLO,
        DEFEATED_BOOMER_KWANGER,
        DEFEATED_CHILL_PENGUIN,
        DEFEATED_LAUNCH_OCTOPUS,
        DEFEATED_SPARK_MANDRILL,
        DEFEATED_STING_CHAMELEON,
        DEFEATED_STORM_EAGLE,
        DEFEATED_FLAME_MAMMOTH,
        ACQUIRED_HEART_TANK_ARMORED_ARMADILLO_STAGE,
        ACQUIRED_HEART_TANK_BOOMER_KWANGER_STAGE,
        ACQUIRED_HEART_TANK_CHILL_PENGUIN_STAGE,
        ACQUIRED_HEART_TANK_LAUNCH_OCTOPUS_STAGE,
        ACQUIRED_HEART_TANK_SPARK_MANDRILL_STAGE,
        ACQUIRED_HEART_TANK_STING_CHAMELEON_STAGE,
        ACQUIRED_HEART_TANK_STORM_EAGLE_STAGE,
        ACQUIRED_HEART_TANK_FLAME_MAMMOTH_STAGE,
        ACQUIRED_SUB_TANK_ARMORED_ARMADILLO_STAGE,
        ACQUIRED_SUB_TANK_SPARK_MANDRILL_STAGE,
        ACQUIRED_SUB_TANK_STORM_EAGLE_STAGE,
        ACQUIRED_SUB_TANK_FLAME_MAMMOTH_STAGE,
        ACQUIRED_BOOTS,
        ACQUIRED_ARMOR,
        ACQUIRED_MEGA_BUSTER,
        ACQUIRED_HELMET
    };

    std::ostream& operator<<(std::ostream&, Achievement);
}

#endif