#ifndef ACHIEVEMENTS_CPP
#define ACHIEVEMENTS_CPP

#include <array>

#include "constants.cpp"

using namespace std;

enum Achievements {
    DEFEATED_ARMORED_ARMADILLO,
    DEFEATED_BOOMER_KWANGER,
    DEFEATED_CHILL_PENGUIN,
    DEFEATED_LAUNCH_OCTOPUS,
    DEFEATED_SPARK_MANDRILL,
    DEFEATED_STING_CHAMELEON,
    DEFEATED_STORM_EAGLE,
    DEFEATED_FLAME_MAMMOTH,
    ACQUIRED_HEART_TANK_ARMORED_ARMADILLO_STAGE,
    ACQUIRED_HEART_TANK_BOOMER_KWANGER_STAGE,
    ACQUIRED_HEART_TANK_CHILL_PENGUIN_STAGE,
    ACQUIRED_HEART_TANK_LAUNCH_OCTOPUS_STAGE,
    ACQUIRED_HEART_TANK_SPARK_MANDRILL_STAGE,
    ACQUIRED_HEART_TANK_STING_CHAMELEON_STAGE,
    ACQUIRED_HEART_TANK_STORM_EAGLE_STAGE,
    ACQUIRED_HEART_TANK_FLAME_MAMMOTH_STAGE,
    ACQUIRED_SUB_TANK_ARMORED_ARMADILLO_STAGE,
    ACQUIRED_SUB_TANK_SPARK_MANDRILL_STAGE,
    ACQUIRED_SUB_TANK_STORM_EAGLE_STAGE,
    ACQUIRED_SUB_TANK_FLAME_MAMMOTH_STAGE,
    ACQUIRED_BOOTS,
    ACQUIRED_ARMOR,
    ACQUIRED_MEGA_BUSTER,
    ACQUIRED_HELMET,
    _SIZE
};

enum AchievementsRealized {
    NONE,
    FIRST,
    SECOND,
    BOTH
};

typedef array<unsigned short, 2> achievements;

typedef array<array<achievements, PASSWORD_GRID_X_SIZE>, PASSWORD_GRID_Y_SIZE> achievementsPositions;

const achievementsPositions ACHIEVEMENTS_POSITIONS =
{{
    {{ // y: 0
        {{ // x: 0
            ACQUIRED_HEART_TANK_CHILL_PENGUIN_STAGE,
            ACQUIRED_SUB_TANK_ARMORED_ARMADILLO_STAGE
        }},
        {{ // x: 1
            DEFEATED_FLAME_MAMMOTH,
            ACQUIRED_HELMET
        }},
        {{ // x: 2
            ACQUIRED_HEART_TANK_FLAME_MAMMOTH_STAGE,
            ACQUIRED_SUB_TANK_FLAME_MAMMOTH_STAGE
        }},
        {{ // x: 3
            DEFEATED_STORM_EAGLE,
            ACQUIRED_HEART_TANK_STORM_EAGLE_STAGE
        }}
    }},
    {{ // y: 1
        {{ // x: 0
            DEFEATED_LAUNCH_OCTOPUS,
            ACQUIRED_ARMOR
        }},
        {{ // x: 1
            DEFEATED_BOOMER_KWANGER,
            ACQUIRED_HEART_TANK_BOOMER_KWANGER_STAGE
        }},
        {{ // x: 2
            DEFEATED_ARMORED_ARMADILLO,
            ACQUIRED_MEGA_BUSTER
        }},
        {{ // x: 3
            DEFEATED_SPARK_MANDRILL,
            ACQUIRED_HEART_TANK_STING_CHAMELEON_STAGE
        }}
    }},
    {{ // y: 2
        {{ // x: 0
            ACQUIRED_HEART_TANK_ARMORED_ARMADILLO_STAGE,
            ACQUIRED_BOOTS
        }},
        {{ // x: 1
            DEFEATED_STING_CHAMELEON,
            ACQUIRED_SUB_TANK_STORM_EAGLE_STAGE
        }},
        {{ // x: 2
            ACQUIRED_HEART_TANK_LAUNCH_OCTOPUS_STAGE,
            ACQUIRED_SUB_TANK_SPARK_MANDRILL_STAGE
        }},
        {{ // x: 3
            DEFEATED_CHILL_PENGUIN,
            ACQUIRED_HEART_TANK_SPARK_MANDRILL_STAGE
        }}
    }}
}};

#endif